name: Gradle Publish

on:
  workflow_dispatch:
    inputs:
      interlok-repo:
        description: 'Interlok Repo (e.g. adaptris/interlok)'
        type: string
        required: true
      disable-dependency-check:
        description: 'Disable OWASP dependency check step'
        default: false
        required: false
        type: boolean
      runs-on:
        description: 'Runner lable, default to ubuntu-latest'
        default: 'ubuntu-latest'
        required: false
        type: string

jobs:
  gradle-publish:
    name: Gradle Publish

    runs-on: ${{ inputs.runs-on }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.interlok-repo }}
        ref: develop
        token: ${{ secrets.GH_READONLY_PAT }}
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: wrapper
    - name: Execute Gradle build
      run: ./gradlew -Djava.security.egd=file:/dev/./urandom -Dorg.gradle.console=plain --no-daemon -PverboseTests=true check
      env:
        ORG_GRADLE_PROJECT_repoUsername: deployment
        ORG_GRADLE_PROJECT_repoPassword: ${{ secrets.NEXUS_REPO_PASSWORD }}
    - name: Upload Test Report
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: '**/build/reports/tests/test/'
        retention-days: 2
    - name: Upload Spotbugs Report
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: spotbugs-report
        path: '**/build/reports/spotbugs/'
        retention-days: 2
    - name: Upload Jacoco Report
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: '**/build/reports/jacoco/test/html/'
        retention-days: 2
    - name: codecov.io
      if: ${{!github.event.repository.private}}
      uses: codecov/codecov-action@v4.6.0
    - name: Gradle Dependency Check Analyze
      if: ${{ inputs.disable-dependency-check != true }}
      run: ./gradlew -Djava.security.egd=file:/dev/./urandom -Dorg.gradle.console=plain --no-daemon dependencyCheckAnalyze
    - name: Upload OWASP Dependency Check Report
      if: ${{ inputs.disable-dependency-check != true }}
      uses: actions/upload-artifact@v4
      with:
        name: owasp-dependency-check-report
        path: '**/build/reports/dependency-check-report.html'
        retention-days: 2
    - name: Publish package
      if: success()
      run: ./gradlew -Djava.security.egd=file:/dev/./urandom -Dorg.gradle.console=plain --no-daemon publish -x test
      env:
        ORG_GRADLE_PROJECT_repoUsername: deployment
        ORG_GRADLE_PROJECT_repoPassword: ${{ secrets.NEXUS_REPO_PASSWORD }}
