name: Maven Publish

on:
  workflow_dispatch:

env:
  PUBLISH_SERVER: 'adaptris-snapshots'

jobs:
  gradle-publish:
    name: Gradle Publish

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: adaptris/interlok-ui
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 11
    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Execute Maven build
      run: |
        cd adapter-web-gui
        mvn --batch-mode -Phudson test
    - name: codecov.io
      if: ${{!github.event.repository.private}}
      uses: codecov/codecov-action@v3.1.4
    - name: Gradle Dependency Check Analyze
      run: |
        cd adapter-web-gui
        mvn -Dskip.owasp=true dependency-check:check
    - name: Set up maven settings.xml
      uses: s4u/maven-settings-action@v3.0.0
      with:
        servers: '[{"id": "${{ env.PUBLISH_SERVER }}", "username": "deployment", "password": "${{ secrets.NEXUS_REPO_PASSWORD }}"}]'
    - name: Publish package
      if: success()
      run: |
        cd adapter-web-gui
        mvn --batch-mode -Pnightly deploy
